FROM mcr.microsoft.com/dotnet/sdk:3.1 as dependencies
WORKDIR /build
COPY ./bankOfMumAndDad/*.csproj ./bankOfMumAndDad/
COPY ./*.sln ./
RUN dotnet restore

FROM dependencies as build
COPY ./bankOfMumAndDad/ ./bankOfMumAndDad/
RUN dotnet publish "./bankOfMumAndDad/bankOfMumAndDad.csproj" -c release -o "./out" --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:3.1 as final
WORKDIR /app
COPY --from=build /build/out/ ./
ENV ASPNETCORE_ENVIRONMENT=Development
EXPOSE 55471
ENTRYPOINT ["dotnet", "bankOfMumAndDad.dll", "--urls", "http://0.0.0.0:55471"]